### ISSUE TITLE
Reporte de interfaz grafica 

### ISSUE THREAD

**Issue by MLR062998** [SistemasTecTlaxiaco/practica-de-visual-studio-MLR062998#2]
[interfaz grafica.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-visual-studio-MLR062998/files/6770270/interfaz.grafica.pdf)

**Comment by Aricel117** [comment]
Excelente trabajo compañero 
Calificacion: 20 pts

**Comment by josealfredo79** [comment]
esta bien hecho y revisado,, pero no se puede otorgar la máxima calificación por entregar al final del semestre
